CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Produtos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text NOT NULL,
    "Descricao" text NOT NULL,
    "Preco" numeric NOT NULL,
    "Estoque" integer NOT NULL,
    CONSTRAINT "PK_Produtos" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260828235347_InitialCreate', '9.0.11');

ALTER TABLE "Produtos" ADD "Categoria" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260828235915_AdicionarCategoria', '9.0.11');

ALTER TABLE "Produtos" DROP COLUMN "Categoria";

ALTER TABLE "Produtos" ADD "CategoriaId" integer NOT NULL DEFAULT 0;

CREATE TABLE "Categorias" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text NOT NULL,
    "Descricao" text NOT NULL,
    CONSTRAINT "PK_Categorias" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Produtos_CategoriaId" ON "Produtos" ("CategoriaId");

ALTER TABLE "Produtos" ADD CONSTRAINT "FK_Produtos_Categorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES "Categorias" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260829000640_CriarTabelaCategorias', '9.0.11');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260829005302_CriarTabelaCateogiras', '9.0.11');

CREATE TABLE "Usuarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text NOT NULL,
    "Email" text NOT NULL,
    "Senha" text NOT NULL,
    "Role" text NOT NULL,
    "CriadoEm" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260830141506_CriarTabelaUsuarios', '9.0.11');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260830144017_AdicionarDbSetUsuarios', '9.0.11');

COMMIT;

